version: '3.7'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    mem_limit: 1G
    mem_reservation: 128M
    cpus: 1
    environment:
      - POSTGRES_USER=rock
      - POSTGRES_PASSWORD=rock
      - POSTGRES_DB=rockstar